# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_SERVER'] %>
  database: <%= ENV['APP_DB_NAME'] %>
  pool: 5
  username: <%= ENV['APP_DB_USER'] %>
  password: <%= ENV['APP_DB_PASS'] %>
  port: <%= ENV['POSTGRES_PORT'] %>
